### ISSUE TITLE
Make widget less intrusive on mobile

### ISSUE THREAD

**Issue by wearecast** [TechforgoodCAST/cast-website#102]
According to this blog, Google is now penalising interstitials the block most of the screen in its search ranking. https://webmasters.googleblog.com/2016/08/helping-users-easily-access-content-on.html?m=1

Reckon ours is guilty of that on mobile... Any way we can have just the question appear on mobile but with the answers as a drop-down?

**Comment by andrewMacmurray** [comment]
@wearecast have changed it back to the less obtrusive version, let us know what you think

**Comment by eghale** [comment]
Much better thanks :) 👍
