### ISSUE TITLE
Change header image on mobile

### ISSUE THREAD

**Issue by eghale** [TechforgoodCAST/cast-website#104]
Small point but our header currently looks a bit puny on mobile, so suggest we replace headerImage with the zoomed-in logo I've saved at cast-website/source/images/headerimagemobile.png

Couldn't actually make this work when I tried it at the weekend though, @ivanmauricio @andrewMacmurray maybe you could take a look (perhaps it wouldn't change on inspect element but would if I actually altered the code?)

**Comment by andrewMacmurray** [comment]
@eghale will have a look at this now

**Comment by andrewMacmurray** [comment]
closed with pr #107

**Comment by eghale** [comment]
Thanks @andrewMacmurray :) 👍
