### ISSUE TITLE
Redo CSS with Tachyons

### ISSUE THREAD

**Issue by andrewMacmurray** [TechforgoodCAST/cast-website#112]
@ivanmauricio and I have been thinking the css on the site is going to quickly get out of control.

we've been using this css methodology ("functional css") on a couple of projects and it's extremely flexible and means the size of the css file doesn't really grow as the project grows larger.

http://tachyons.io/

I went to a talk by [tableflip](https://tableflip.io/) (a web consultancy company) recently and they have moved over to tachyons exclusively now.

We were thinking it might be a good idea to implement this as we're going to be adding a lot more content to the site

**Comment by eghale** [comment]
You guys are going to have to talk me through this today because I am a bit lost without Bootstrap...!
😧

**Comment by andrewMacmurray** [comment]
@eghale that's ok we can walk you through it. Tachyons / functional css is a fantastic modern css methodology and well worth learning, it's quite a simple principal but it's very powerful
