### ISSUE TITLE
Bugs with reimplemented CSS

### ISSUE THREAD

**Issue by ivan-unfolds** [TechforgoodCAST/cast-website#129]

**Comment by ivan-unfolds** [comment]
@eghale - couple of points - h2 should be Helvetica and not Roboto Slab, and the image sizing needs a bit of tweaking as the pics in the Our Work and Get Involved sections are now pretty small as there's quite a lot of padding on them (looks especially odd on tablet size)

![screen shot 2017-03-01 at 11 17 17](https://cloud.githubusercontent.com/assets/11066569/23457635/af3e0c40-fe70-11e6-8764-179124a9b72e.png)

Should be 

![screen shot 2017-03-01 at 11 17 53](https://cloud.githubusercontent.com/assets/11066569/23457655/c128c134-fe70-11e6-9020-8eccb050f60b.png)

**Comment by eghale** [comment]
![screen shot 2017-03-01 at 10 48 55](https://cloud.githubusercontent.com/assets/11066569/23457098/4def2070-fe6e-11e6-9586-ce5d3e688139.png)

Beehive logo not centred on tablet view (despite saying it is in the html!) 

Also the Tech for Good logo seems particularly small, you may have to make it slightly bigger than the others proportionally just to make it look about the same!

**Comment by eghale** [comment]
![screen shot 2017-03-01 at 10 51 46](https://cloud.githubusercontent.com/assets/11066569/23457115/66b954fe-fe6e-11e6-97bf-07edf4a36928.png)

Uneven line spacing on tablet view

**Comment by eghale** [comment]
![screen shot 2017-03-01 at 10 53 07](https://cloud.githubusercontent.com/assets/11066569/23457133/88b177a8-fe6e-11e6-827b-1819f47488c3.png)

This is what I mean about the padding - could you take it down from 32 (as in above, new example) to 15 as in the below? Or even lower like 5...

**Comment by eghale** [comment]
![screen shot 2017-03-01 at 10 47 56](https://cloud.githubusercontent.com/assets/11066569/23457331/5cef19d0-fe6f-11e6-8789-b930acef27e9.png)

Modals have gone epicly wide on web view. Look OK on mobile and tablet though.

**Comment by eghale** [comment]
Sorry, just caught a couple more on tablet view. 

1) Beehive logo is huge, other 'Get Involved' images are tiny:

![screen shot 2017-03-07 at 18 54 34](https://cloud.githubusercontent.com/assets/11066569/23672791/c3832518-0367-11e7-9adf-117cbca65f67.png)

2) H5 and H6 text on the Team and Board sections is too small, especially on tablet view. Could this be H4 and p instead? Maybe the names can just be <b>h4</b> to differentiate?

![screen shot 2017-03-07 at 18 54 50](https://cloud.githubusercontent.com/assets/11066569/23672884/16789eb0-0368-11e7-816d-5c5a9a0fbd2f.png)
