### ISSUE TITLE
Fellowship document upload

### ISSUE THREAD

**Issue by eghale** [TechforgoodCAST/cast-website#137]
@ivanmauricio @andrewMacmurray please can we replace the Fellowship modal text with:

To transform the charity sector and enable it to put digital at the heart of its work, we need to support senior charity leaders and CEOs to understand the potential of digital.

Our Digital Fellowship is a carefully constructed learning programme that teaches its fellows the key aspects of the digital development, from paper prototyping to business modelling. We bring the leaders together to learn from industry experts as well as spending time with key organisations leading the field. 

The pilot was funded by Comic Relief in 2016, and culminated in a design sprint with development teams from Founders & Coders for the Fellows to put what they'd learned into practice.

For more information on our Digital Fellowship:
- [Download the 'About' document]
[IntroToDigitalFellowship.docx.pdf](https://github.com/TechforgoodCAST/cast-website/files/857853/IntroToDigitalFellowship.docx.pdf)
- Read about the course structure in our [[Programme review](https://medium.com/@wearecast/creating-digitally-confident-leaders-in-the-social-sector-9d3fd0f7b3ff#.f03g0m5kw)], [[Day 1](https://medium.com/@wearecast/diving-into-the-digital-fellowship-part-1-411119ad5039#.w19fu2yo2)] and [[Day 2](https://medium.com/@wearecast/diving-into-the-digital-fellowship-part-2-cbffa5dda601#.re8iuisdw)] blogs
- Check out this [[Fellowship guest blog from Duncan McLaggan, Operations Manager at QSA](http://www.charitydigitalnews.co.uk/2017/02/15/building-digital-products-in-a-small-to-medium-sized-charity-guest-post/)]
- Watch this short video of the Fellows' own thoughts and testimonials [embedded in page if possible] https://www.youtube.com/watch?v=ODAYSZXw_uE&t=4s

So the bottom is a list of bullet points basically, with an embedded video if that's doable (otherwise a link will have to do).

**Comment by eghale** [comment]
Just to clarify, the square brackets indicate links, so the first one should automatically download the document and the others go to the blog posts or video. But the square brackets aren't included in the copy :) Here's the GDrive link to the "About" Fellowship doc if that's easier: https://docs.google.com/document/d/1Bm2oiDtk0qmBUJnnX-0u6nQG4wdA6rqiLNfusvTj-Vs/edit

Shout if any questions!

**Comment by eghale** [comment]
Update document with this refreshed version: https://docs.google.com/document/d/1Bm2oiDtk0qmBUJnnX-0u6nQG4wdA6rqiLNfusvTj-Vs/edit

**Comment by eghale** [comment]
Hi @andrewMacmurray @ivanmauricio - please could you update the doc linked with the updated version above? Thanks!

**Comment by eghale** [comment]
Seems to have broken another part of the design..

![screen shot 2017-04-04 at 12 42 39](https://cloud.githubusercontent.com/assets/11066569/24655027/471a7908-1934-11e7-8809-d07e689c9af0.png)

**Comment by andrewMacmurray** [comment]
cant seem to replicate this, try reloading your page?

**Comment by eghale** [comment]
Cool, all good now! Ship it :) :shipit:
