### ISSUE TITLE
Bug fixes on Fuse site

### ISSUE THREAD

**Issue by eghale** [TechforgoodCAST/cast-website#138]
@ivanmauricio @andrewMacmurray 

1) 'Graduates' modal quotes should be formatted the same for each box - see discrepancy below

![screen shot 2017-03-21 at 11 15 45](https://cloud.githubusercontent.com/assets/11066569/24145171/e21fe6da-0e27-11e7-9b69-1f968b1d941b.png)
![screen shot 2017-03-21 at 11 15 32](https://cloud.githubusercontent.com/assets/11066569/24145174/e482a430-0e27-11e7-9882-df34f25f0b45.png)

2) Oxfam, Breast Cancer Care, Age UK and Centrepoint should all be on the first line together (as they were the first cohort) and Women's Aid, Advising London and Clore on the second line together

3) Parkinson's UK logo is weirdly squished, could you find a better one/unsquish it?
![screen shot 2017-03-21 at 11 23 25](https://cloud.githubusercontent.com/assets/11066569/24145394/e1efbca2-0e28-11e7-8b0d-61dc71d09c64.png)

4) Women's Aid logo seems smaller/lower res than the others, could you find a better quality version?
![screen shot 2017-03-21 at 11 18 06](https://cloud.githubusercontent.com/assets/11066569/24145229/23a1c10a-0e28-11e7-98f4-f00282fb4766.png)

5) Super Being Labs should really be in the 'Supporters and Partners' section, not 'The Team' section. Also we need to add a Health Foundry logo to 'Supporters and Partners' as well.

**Comment by andrewMacmurray** [comment]
@eghale 

1 - which quote format would you like?
5 - Do you have a health foundry logo we can use?

**Comment by eghale** [comment]
1. The italics one please

5. I don't i'm afraid, is there not one online?
