### ISSUE TITLE
Additional Our Work modals

### ISSUE THREAD

**Issue by eghale** [TechforgoodCAST/cast-website#167]
@andrewMacmurray @ivanmauricio - another job for you guys this week, Dan's keen to update the site ASAP with this new info. Shout if any questions/that's not doable! :)

To replace the current modal boxes with Ufi and Power to Change: 

Comic Relief
[by-line]
Proving support to a leading grant maker in designing and delivering grant programmes that support nonprofit tech for good.

[image]
Can you find a Comic Relief logo for this? 

[content]
Trusts and foundations play a vital role in realising the potential of digital technology to achieve charitable and social impact. We work with grant makers to identify where digital can make the biggest impact in their work, including designing and co-developing grant programmes; assessing applications, and working directly with grantees to support their development and delivery. We're current working with Comic Relief to deliver the [Tech for Good](https://www.comicrelief.com/grants/tech-for-good) fund and to support all grantees in their [Tech Vs Abuse](https://www.comicrelief.com/news/comic-relief-launches-tech-vs-abuse-initiative) funding programme.

Wales Third Sector Skills
[by-line]
Developing an agile mentoring and skills service that can support third sector organisations across Wales.

[image]
![screen shot 2017-05-22 at 12 18 58](https://cloud.githubusercontent.com/assets/11066569/26305980/762d1f22-3ee9-11e7-9cc8-3717cf1ba62b.png)

[content]
​Working with Wales Co-operative Centre, Business in the Community Cymru and Wales Council for Voluntary Action, we're developing a digital service to support third sector organisations across Wales to access skills, mentoring and trustees to build their organisational capacity. Having completed our Digital Fellowship, Derek Walker, CEO of Wales Co-op, secured funding from Big Lottery Wales to follow an agile user-led and test-driven process to identify how digital tools can be developed to provide this new support. We're leading that process to research, prototype and deliver this new digital service to support social organisations across Wales.

**Comment by andrewMacmurray** [comment]
@eghale we can have a go at this tomorrow. Do you want the `Ufi` and `Power to change` modals replaced with the two new ones?

**Comment by andrewMacmurray** [comment]
![comic relief](http://images.dailystar.co.uk/dynamic/1/photos/882000/620x/46882.jpg) ?

**Comment by eghale** [comment]
Yes please @andrewMacmurray :) Logo is perfect. Merci buckets!
