### ISSUE TITLE
Move Parkinson's UK to Alumni section and update copy

### ISSUE THREAD

**Issue by ToriCAST** [TechforgoodCAST/cast-website#172]
Can we please move Parkinson's UK down to the Alumni section and update the copy to the following. Thanks! 

Every year over 10,000 people are diagnosed with Parkinson’s. The information and support they receive at the point of diagnosis remains inconsistent, and while some people are overloaded with information they’re not yet ready for, others leave the consulting room into the unknown.

Parkinson’s UK joined the Fuse programme to develop a better understanding of how to connect newly diagnosed people to the charity’s information and support services. Speaking to people affected by Parkinson’s raised a common theme - it’s just too difficult to navigate the information and support available and work out what service best meets their needs.

From the user research, a signposting tool was developed and is just about to be launched as an open Beta. The analysis and feedback from this testing stage will be crucial in future iterations, and essential in ensuring the product is fully integrated into the Parkinson’s UK roadmap.

“Through the guidance and support of the team at Fuse, we are now armed with the right skills and understanding of user-centred design and rapid product development to take this exciting project forward. Keen to put what we’ve learnt into practice, we’ve now built an Innovation Lab in our London office, in the hope to foster a creative and innovative culture across the organisation.”

Claire Edwards, Digital Product Manager

**Comment by ivan-unfolds** [comment]
@ToriCAST Do you have an image for the modal?

**Comment by eghale** [comment]
![image uploaded from ios 3 2](https://user-images.githubusercontent.com/11066569/27232010-75d5a70c-52ac-11e7-8b19-72396cefc290.jpg)

How about this? :)
