### ISSUE TITLE
www redirect

### ISSUE THREAD

**Issue by suninthesky** [TechforgoodCAST/cast-website#184]
**Issue**
http://wearecast.org.uk/ returns 123-reg holding page

**Proposed solution**
123-reg provides an easy way to set up permanent forwarding - [details here](https://www.123-reg.co.uk/support/answers/how-do-i-add-301-permanent-web-forwarding-2520/)

**Comment by ivan-unfolds** [comment]
@suninthesky I'm happy to take this on. Do you know if we have login details for 123-reg?

**Comment by suninthesky** [comment]
Thanks @ivanmauricio. I don't unfortunately. @kieronk will have it when he returns in a couple of weeks.

**Comment by ivan-unfolds** [comment]
Fixed this by updating DNS records on 123-reg -

![screen shot 2017-09-18 at 10 31 17](https://user-images.githubusercontent.com/12462448/30536184-ca262e54-9c5c-11e7-9334-4bd63e7e2ef0.png)
![screen shot 2017-09-18 at 10 32 29](https://user-images.githubusercontent.com/12462448/30536186-cc52db46-9c5c-11e7-8ec3-be88edf298cb.png)
