### ISSUE TITLE
Fuse site logo updates on 'The Team': Change Founders & Coders to DWYL, add Cantor & Ball

### ISSUE THREAD

**Issue by eghale** [TechforgoodCAST/cast-website#45]
Kieron sourcing Cantor & Ball logo, Ellie sourcing DWYL.

**Comment by ivan-unfolds** [comment]
@eghale What needs to be done for this issue?

**Comment by eghale** [comment]
Crikey that was an old one. I think we need a bit more of a review of the different agencies we have on here now anyway rather than just these two changes, so maybe pause this for now...
