### ISSUE TITLE
Fix newsletter sign-up - still buggy

### ISSUE THREAD

**Issue by eghale** [TechforgoodCAST/cast-website#56]
![f3d988a2-3c2f-4285-bc91-cab738ffda84](https://cloud.githubusercontent.com/assets/11066569/18523539/89bfd6f8-7aac-11e6-9aac-7b65dd672f02.png)

**Comment by suninthesky** [comment]
@eghale Worked for me with those same details. The [docs](http://kb.mailchimp.com/accounts/management/about-error-messages), suggest 

> Wait several minutes to see if you are able to successfully sign up with the email address or try a different browser. If your browser has an auto-fill setting, try turning it off—it can fill a hidden field that we include in the code to prevent spam signups.

We can remove the said hidden field, but it increase the changes of spam sign ups.

**Comment by eghale** [comment]
Yeah it's the same issue we faced last time. I don't think it should be too much of an issue if we remove the spam filter... Perhaps worth a try anyway. I'd rather do that than get more people trying to sign up and emailing us when they can't (which is as annoying as spam imo).

**Comment by suninthesky** [comment]
Sure thing, have removed the hidden field https://github.com/TechforgoodCAST/cast-website/commit/da8b9ec2be56e12917d12d1fc8d2b3a295ddd444.
