### ISSUE TITLE
Sitemap and Structure

### ISSUE THREAD

**Issue by andrewMacmurray** [TechforgoodCAST/cast-website#64]
Here is what we've distilled so far from the post-it notes session from [yesterday](https://drive.google.com/drive/folders/0B8Wb9pceJ4GZZGloQ1ZrbjdfR3c)

+ Home
  + Brief mission statement
  + Carousel (Current opportunities, events and other things)
  + Who we are what we do
  + Signup to newsletter

+ About
  + Who we are what we do
  + Team
  + Impact stats (case studies)
  + Timeline
  + Press
  + Governance
  + Partners

+ What we do (tagged and filterable items)
  + Services
  + Products
  + Alumni?

+ Get Involved
  + Sign up to specific program
  + Sign up to newsletter
  + Resources
  + Contact CAST
  + Hiring

@eghale @suninthesky Would be great if you two have any thoughts on this to detail them here, we'll probably need some more clarification on particular bits as we go along.

**Comment by ivan-unfolds** [comment]
Specifically we were wondering about -

* What will be going in the **Alumni** section?
* Whether **Resources** needs its own page or whether it can go under **Get Involved**?

**Comment by andrewMacmurray** [comment]
After discussion with @eghale about resources section, it should have its own page

**Comment by andrewMacmurray** [comment]
closed for now as implementing slightly different approach to redeveloping website
