### ISSUE TITLE
Widget for survey on homepage

### ISSUE THREAD

**Issue by andrewMacmurray** [TechforgoodCAST/cast-website#71]
Need some way of getting the user to submit survey information on the homepage

**Comment by andrewMacmurray** [comment]
potential solutions

+ google forms (could send people to a form and get the data from there)
+ [get site control survey widget](https://getsitecontrol.com/survey-widget/#flyby-right) (very comprehensive, could be a good interim solution)

**Comment by andrewMacmurray** [comment]
@eghale we have a working version of the survey on the staging site, have a look when you get a moment: http://wearecast-staging.herokuapp.com/

there are lots of options to customise it so we can play around with them

**Comment by eghale** [comment]
This widget looks great :)

**Comment by eghale** [comment]
Actually - that was possibly premature as I hadn't actually submitted the answers on it - could we change the wording at the end to 'Your feedback will help us make this site more useful'?

**Comment by eghale** [comment]
And maybe add a 'Please specify' option to the 'Other' category in the second 'Do you work for a...?' menu. 

Sorry for fragmented feedback. That's everything... I think :)

**Comment by andrewMacmurray** [comment]
@eghale ok, have made those changes, if you're happy with them we can merge them into the main site at the end of the day

**Comment by eghale** [comment]
I can't see the widget on the staging app any more, just lots of rounded corners... (which look great, btw)

**Comment by andrewMacmurray** [comment]
@eghale Ah, it disappears after you've submitted it once, to see it again open the staging site in a private browsing window (shortcut is `shift` `command` `n`)

**Comment by eghale** [comment]
Cool looks good - I'd maybe even add a smiley after 'useful' as we want to be super friendly, but that's just my style :)

Happy for you to push this live, look forward to seeing some real user data from it!

**Comment by andrewMacmurray** [comment]
smiley added, will merge into production shortly
