### ISSUE TITLE
Come up with survey questions

### ISSUE THREAD

**Issue by ivan-unfolds** [TechforgoodCAST/cast-website#73]
links #71

**Comment by eghale** [comment]
Here are the questions:

1. Do you work for a...?
- Charity
- Startup
- Funder
- Tech/design agency
- Government
- Freelance
- Other

2. What are you looking for?
- Support with a tech for good project
- Support with digital skills and confidence
- Information about CAST
- Funding
- Jobs
- Just browsing

**Comment by andrewMacmurray** [comment]
@eghale brilliant, thanks! will get these up and running on the staging site and we can see how they work
