### ISSUE TITLE
Copy and images for Advising London, Clore and Women's Aid

### ISSUE THREAD

**Issue by ivan-unfolds** [TechforgoodCAST/cast-website#80]
We need these resources to update FUSE site.

**Comment by eghale** [comment]
Doc is here, but these are not 100% signed off yet - will let you know when they are!

https://docs.google.com/document/d/1nkMYdIgUDPYr-TnpbzqRyJRo9ltNl1134gK7HP-HNRQ/edit#

**Comment by eghale** [comment]
The doc is now signed off, hurrah! Here are the images :)
![womensaidworkshop](https://cloud.githubusercontent.com/assets/11066569/23309657/7470ac70-faa7-11e6-985c-8d33cac61f7a.jpg)

![advisinglondonimage](https://cloud.githubusercontent.com/assets/11066569/23309997/c58b479a-faa8-11e6-9810-7def5d8e8c60.jpg)

![cloreimage](https://cloud.githubusercontent.com/assets/11066569/23309999/c78af61c-faa8-11e6-8c09-3e414e0ca70e.JPG)
