### ISSUE TITLE
Visualising the progress charts for the ‘impact’ section

### ISSUE THREAD

**Issue by andrewMacmurray** [TechforgoodCAST/cast-website#90]
@eghale @suninthesky could you perhaps leave some more details of what you were thinking here?

**Comment by suninthesky** [comment]
I'd say this is an idea for the backlog, not something to put energy towards developing now. @eghale suggest removing from current milestone.

**Comment by eghale** [comment]
Sure, makes sense - happy for it to move to backlog. This was more of the dashboard idea so one to revisit once the main site changes are all done.
