### ISSUE TITLE
Newsletter sign-up

### ISSUE THREAD

**Issue by eghale** [TechforgoodCAST/cast-website#97]
The Mailchimp entry form on the bottom of the main page gone all wide and ugly. Could you fix back to neat narrow version plz? Ta!

**Comment by andrewMacmurray** [comment]
@eghale I'm not sure I understand what you mean, could you take a picture and post it here?

**Comment by andrewMacmurray** [comment]
@eghale is this on the main or the staging site?

**Comment by eghale** [comment]
![screen shot 2017-02-14 at 15 18 18](https://cloud.githubusercontent.com/assets/11066569/22935086/4adbc6be-f2c9-11e6-8da4-3d90279afdfd.png)

**Comment by ivan-unfolds** [comment]
@eghale Having trouble replicating that. What browser are you on? I don't think we have touched the styling for this.

**Comment by andrewMacmurray** [comment]
closing, seems like it's fixed on @eghale 's computer
