### ISSUE TITLE
Content for our work section

### ISSUE THREAD

**Issue by andrewMacmurray** [TechforgoodCAST/cast-website#98]
@eghale content here please 👾 ✨ 😄

**Comment by eghale** [comment]
@andrewMacmurray Here's a link to the Design Hop page - if you could make a start mocking this up that'd be fab https://docs.google.com/document/d/1m-KqhZfeVYodZoHr-Z313MnA8j9Ml6zvQonpgzzGfl8/edit#heading=h.l8uhy5lrd4z0 

Finishing the others now, and still wrangling with how to display them all together on the main page! 🤔
